=== arevell/test/ch2-brox/src/main/resources/bookend/TT/terms-schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="terms">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded" minOccurs="2">
				<xs:element ref="Title" />
				<xs:element ref="Section1" />
			</xs:choice>
			<xs:attribute name="currency_symbol" type="xs:string" />
			<xs:attribute name="papersize" type="xs:string" />
			<xs:attribute name="dateFormat" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="Title" type="xs:string"/>
	<xs:element name="Section1">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element ref="Title" />
				<xs:element ref="Section2" />
				<xs:element ref="Image" />
			</xs:choice>
			<xs:anyAttribute />
		</xs:complexType>
	</xs:element>
	<xs:element name="Section2">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="Title" />
				<xs:element ref="Text" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="Text">
		<xs:complexType  mixed="true">
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="strong" />
				<xs:element ref="p" />
				<xs:element ref="div" />
				<xs:element ref="a" />
				<xs:element ref="br" />
				<xs:element ref="ul" />
				<xs:element ref="ol" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="text">
		<xs:complexType  mixed="true">
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="strong" />
				<xs:element ref="i" />
				<xs:element ref="p" />
				<xs:element ref="div" />
				<xs:element ref="a" />
				<xs:element ref="br" />
				<xs:element ref="ul" />
				<xs:element ref="ol" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="div">
		<xs:complexType  mixed="true">
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="strong" />
				<xs:element ref="i" />
				<xs:element ref="p" />
				<xs:element ref="div" />
				<xs:element ref="a" />
				<xs:element ref="br" />
				<xs:element ref="ul" />
				<xs:element ref="ol" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="strong">
		<xs:complexType  mixed="true">
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="i" />
				<xs:element ref="a" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="i">
		<xs:complexType  mixed="true">
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="strong" />
				<xs:element ref="a" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="a">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="href" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="p">
		<xs:complexType  mixed="true">
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="strong" />
				<xs:element ref="i" />
				<xs:element ref="a" />
				<xs:element ref="br" />
				<xs:element ref="ul" />
				<xs:element ref="ol" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="br">
		<xs:simpleType>
			<xs:restriction base="xs:string">
  				<xs:length value="0"/>
  			</xs:restriction>
 		</xs:simpleType>
	</xs:element>
	<xs:element name="ul">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element ref="li" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="ol">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element ref="li" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="li">
		<xs:complexType  mixed="true">
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="strong" />
				<xs:element ref="p" />
				<xs:element ref="div" />
				<xs:element ref="a" />
				<xs:element ref="br" />
				<xs:element ref="ul" />
				<xs:element ref="ol" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="ti">
		<xs:complexType  mixed="true">
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="strong" />
				<xs:element ref="p" />
				<xs:element ref="div" />
				<xs:element ref="a" />
				<xs:element ref="br" />
				<xs:element ref="ul" />
				<xs:element ref="ol" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="Image" type="xs:string"/>
</xs:schema>

=== arevell/test/ch2-brox/src/main/resources/bookend/TT/terms.TTOTHS.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<terms papersize="A4" currency_symbol="&#163;" xsi:noNamespaceSchemaLocation="terms-schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> 
    <Title>Terms &amp; Conditions</Title>
    <Section1>  
        <Title>GENERAL INFORMATION AND CONDITIONS</Title>
        <Section2>
            <Title>Holiday Prices</Title>
            <Text><strong>Prices are per person.</strong>
                Prices are per person. Prices are 
                based on costs, charges, tariffs, rates, prices,
                taxes, levies and exchange rates as at the
                time Trafalgar&apos;s main brochures were printed. Should
                these change, the price of your holiday
                may increase. No surcharges in respect of
                cost or currency fluctuations will be made
                once payment for the deposit of the land portion of your
                holiday is received. This does not apply to
                fuel surcharges and any taxes, charges or
                levies imposed by any government or their
                agencies. In exchange for these guarantees,
                no refund will be made if costs are reduced.
                Please note that if the total holiday price
                increases by more than 10%, guests will
                have the right to cancel their holiday within 7
                days of notification of the surcharge without
                penalty.
            </Text>
        </Section2>
        <Section2>
            <Title>Holiday Cancellation</Title>
            <Text>Trafalgar reserves the right to cancel or reschedule
                any holiday departure in accordance
                with operating requirements or circumstances
                beyond its control. If cancellation is made
                any time prior to departure of the holiday,
                Trafalgar&apos;s only liability will be to refund to
                the guest the amount it has received
                for the holiday booking. Trafalgar will try to rebook
                the same or similar holiday and, 
                <strong>where flights have been confirmed by Trafalgar,
                </strong>will attempt to confirm air seats for new
                dates selected, subject to availability. Please
                note that Trafalgar is not liable for any
                cancellation penalties incurred on any other
                travel arrangements including air tickets
                purchased separately from the Air + Land
                inclusive package.
            </Text>
            <Text><strong>Trafalgar is not responsible</strong> for any other travel arrangement
                affected due to our cancellations.
                <br/>
                <strong>Full Booking Conditions</strong><br/>
                Other terms and booking conditions apply. Please visit <a href="http://www.trafalgar.com/OTH/conditions">www.trafalgar.com/OTH/conditions</a> for complete details        
            </Text>
         </Section2>
		 <Image>TTOTHS/terms.jpg</Image>
    </Section1>
</terms>
